server:
  port: 8080

spring:
  application:
    name: article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

endpoints:
  board-article-service:
    url: http://localhost:8081
  board-comment-service:
    url: http://localhost:8082
  board-like-service:
    url: http://localhost:8084
  board-view-service:
    url: http://localhost:8085
