server:
  port: 8084

spring:
  application:
    name: article-like-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:31307/article-like?serverTimezone=UTC
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092